version: "3.3"
services:
  bot:
    build:
      context: .
      dockerfile: dev-Dockerfile
    volumes:
      # host:container
      - "LOCATION_FOR_DATABASE_FILES:/usr/src/app/data"
      - "LOCATION_OF_PROJECTS_DIST_DIRECTORY:/usr/src/app/src"
