version: "3.3"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      # host:container
      - dbData:/usr/src/app/data
volumes:
  dbData:
